Update ci-pipeline.yml

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -3,10 +3,10 @@ name: CICD Pipeline for Feature Branches
 on:
   push:
     branches:
-      - "feature/*"  # Trigger workflow for branches matching feature/*
+      - "feature/*"
   pull_request:
     branches:
-      - "feature/*"  # Trigger workflow for PRs targeting feature/*
+      - "feature/*"
   workflow_dispatch:
 
 permissions:
@@ -27,7 +27,7 @@ jobs:
         node-version: 18
 
     - name: Install Dependencies
-      run: npm i
+      run: npm ci
       working-directory: ./src
 
     - name: Run Tests
@@ -40,7 +40,7 @@ jobs:
     steps:
       - uses: actions/checkout@v4
         with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+          fetch-depth: 0
       - name: SonarQube Scan
         uses: SonarSource/sonarqube-scan-action@v4
         env:
@@ -70,9 +70,9 @@ jobs:
     needs: build
     steps:
       - name: Run Trivy vulnerability scanner
-        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
+        uses: aquasecurity/trivy-action@master
         with:
-          image-ref: 'chucthien03/golden-owl:${{ steps.set-timestamp.outputs.time }}'
+          image-ref: 'chucthien03/golden-owl:${{ needs.build.outputs.time }}'
           format: 'sarif'
           output: 'trivy-results.sarif'
           severity: 'CRITICAL,HIGH'
@@ -81,31 +81,30 @@ jobs:
         with:
           sarif_file: 'trivy-results.sarif'
 
-  deliver:
+  deliver_image:
     runs-on: ubuntu-latest
     needs: trivy_scan
     steps:
     - name: Authenticate with Docker Hub
       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
     - name: Push new image to Docker Hub
-      run: docker push chucthien03/golden-owl:${{ steps.set-timestamp.outputs.time }}
+      run: docker push chucthien03/golden-owl:${{ needs.build.outputs.time }}
 
-  deploy:
+  deploy_test_env:
     runs-on: self-hosted
-    needs: deliver
+    needs: deliver_image
     steps:
     - name: Replace the old image
       run: |
         # Stop and remove the old container
         docker rm -f my-container || true
-
         # Remove unused images with the same name
         docker images chucthien03/golden-owl -q | xargs -r docker rmi -f
-
         # Run the new container
         docker run -dp 80:3000 -p 443:3000 --name my-container chucthien03/golden-owl:${{ needs.build.outputs.time }}
-
         # Verify the container and image
         docker ps
         docker images
- 
+    - name: Verify Deployment Health
+      run: |
+        curl -f http://localhost || echo "Deployment failed"
